# Generated by Django 4.2.29 on 2026-04-07 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('vat_code', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_type', models.CharField(choices=[('PVM', 'VAT Invoice'), ('BE_PVM', 'Invoice without VAT'), ('ISANKSTINE', 'Proforma Invoice')], default='PVM', max_length=20)),
                ('language', models.CharField(choices=[('LT', 'Lithuanian'), ('EN', 'English'), ('RU', 'Russian')], default='LT', max_length=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('seller_name', models.CharField(default='UAB "TEKILA PLIUS"', max_length=255)),
                ('seller_address', models.CharField(default='Justiniškių g. 144B-41, LT05268 Vilnius', max_length=255)),
                ('seller_code', models.CharField(default='300106323', max_length=50)),
                ('seller_vat', models.CharField(default='LT100001696415', max_length=50)),
                ('seller_bank', models.CharField(default='LT35 7044 0600 0800 4199', max_length=100)),
                ('seller_email', models.CharField(default='info@tequila.lt', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.client')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(default='vnt', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.invoice')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('product_type', models.CharField(choices=[('Prekės', 'Goods'), ('Paslaugos', 'Services'), ('Ilgalaikis turtas', 'Fixed Assets'), ('Finansinis turtas', 'Financial Assets')], default='Prekės', max_length=50)),
                ('description1', models.CharField(max_length=255)),
                ('description2', models.CharField(blank=True, max_length=255)),
                ('description3', models.CharField(blank=True, max_length=255)),
                ('description4', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(default='vnt', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('avg_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('weight_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['description1'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.invoice')),
                ('invoice_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='inventory.invoiceline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=255)),
                ('purchase_type', models.CharField(choices=[('Prekės', 'Goods'), ('Paslaugos', 'Services'), ('Ilgalaikis turtas', 'Fixed Assets'), ('Finansinis turtas', 'Financial Assets')], default='Prekės', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(default='vnt', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.product')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], default='TRANSFER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.invoice')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
    ]
