# Generated by Django 4.2.30 on 2026-06-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_activitylog'),
        ('inventory', '0003_supplier_model'),
    ]

    operations = [
    ]
